version: '3.4'

services:
  udemyrabbitmq.watermark.ui:
    container_name: UdemyRabbitMQ.WaterMark.UI
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "UdemyRabbitMQ.WaterMark.UI"
    volumes:
      - /Users/hakancirit/vsdbg/vs2017u5:/remote_debugger:rw

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_udemyrabbitmq.watermark.ui$ \"/app/UdemyRabbitMQ.WaterMark.UI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
      com.microsoft.visual-studio.project-name: "UdemyRabbitMQ.WaterMark.UI"
    tty: true